services:
  - type: web
    name: node-runner
    runtime: node
    plan: free
    numInstances: 1
    region: singapore
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
